// <auto-generated />
using CrudVeiculos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CrudVeiculos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240901231608_CreateVeiculosSchema")]
    partial class CreateVeiculosSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CrudVeiculos.Entities.Cor", b =>
                {
                    b.Property<int>("IdCor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCor"));

                    b.Property<string>("NomeCor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdCor");

                    b.ToTable("Cores");
                });

            modelBuilder.Entity("CrudVeiculos.Entities.MarcaVeiculo", b =>
                {
                    b.Property<int>("IdMarca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMarca"));

                    b.Property<string>("NomeMarca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdMarca");

                    b.ToTable("MarcasVeiculo");
                });

            modelBuilder.Entity("CrudVeiculos.Entities.Veiculo", b =>
                {
                    b.Property<int>("IdVeiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVeiculo"));

                    b.Property<string>("AnoFabricacaoModelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Chassis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FkIdCor")
                        .HasColumnType("integer");

                    b.Property<int>("FkIdMarca")
                        .HasColumnType("integer");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RenavamVeiculo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdVeiculo");

                    b.HasIndex("FkIdCor");

                    b.HasIndex("FkIdMarca");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("CrudVeiculos.Entities.Veiculo", b =>
                {
                    b.HasOne("CrudVeiculos.Entities.Cor", "Cor")
                        .WithMany()
                        .HasForeignKey("FkIdCor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrudVeiculos.Entities.MarcaVeiculo", "Marca")
                        .WithMany()
                        .HasForeignKey("FkIdMarca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cor");

                    b.Navigation("Marca");
                });
#pragma warning restore 612, 618
        }
    }
}
